[project]
name = "stable-diffusion"
version = "0.1.0"
description = "simple-stable-diffusion"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4.0",
    "ruff>=0.6.2",
    "numpy<2.0",
    "tqdm>=4.66.5",
]
